accounts/urls.py
from django.urls import path
from .views import *


app_name = "accounts"

urlpatterns = [
    path('login/', login_view, name='login'),

    path('register/', register_view, name='register'),

    path('logout/', logout_view, name='logout'),


]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from post.views import post_index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', post_index),

    path('post/', include('post.urls')),

    path('accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = "post"

urlpatterns = [
    path('index/', post_index, name='index'),
    path('<slug:slug>', post_detail, name='detail'),
    path('create/', post_create, name="create"),
    # path('<slug:slug>/update', post_update, name="update"),
    path('update/<slug:slug>', post_update, name="update"),
    # path('<slug:slug>/delete', post_delete, name="delete"),
    path('delete/<slug:slug>/', post_delete, name="delete"),
    path('myposts/', my_posts, name="myposts")

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse


def home_view(request):
    if request.user.is_authenticated:
        context = {
            'isim': 'Mustafa'
        }
    else:
        context = {
            'isim': 'Misafir'
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %}BLOG{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="../static/js/jquery.min.js"></script>


{% include 'header.html' %}

{% include 'messages.html' %}



{% block body %}

{% endblock %}

</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-sm bg-dark text-bg-light" role="navigation">

    <div class="container-fluid">

    <ul class="nav navbar-nav navbar-right">

        <a class="nav-link active" aria-current="page" href="/" style="color: white">Anasayfa</a>
        {% if request.user.is_authenticated %}
            <a class="nav-link " href="/post/create/" style="color:white">Post Oluştur</a>
        {% endif %}

        {% if request.user.is_authenticated %}
            <a class="nav-link " href="/post/myposts/" style="color:white">Postlarımm</a>
        {% endif %}


    </ul>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" method="GET" action="{% url 'post:index' %}">
            <div class="input-group">
                <div href="/"></div>
                <label>
                    <input  class="form-control form-control-dark text-bg-dark " type="text" name="q" placeholder="Search on blog" style="width: 500px" value="{{ request.GET.q }}">
                </label>
                <span class="input-group-btn">
            <input class="btn bg-transparent btn-default" type="submit" value="Ara" style="color:white">
                    </span>
            </div>
        </form>



        <ul class="nav navbar-nav navbar-right">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">

                    {% if request.user.is_authenticated and request.user.is_superuser %}
                        <li class="nav-item " style="align-self: end">
                            <a class="nav-link" href="/admin" style="color: white" >Admin</a>
                        </li>
                    {% endif %}


                    {% if request.user.is_authenticated %}
                        <li><a class="nav-link" href="{% url 'accounts:logout' %}" style="color: white"> Çıkış</a></li>
                        <a class="nav-link" style="color: white"> Hoşgeldin, {{ user.username }}</a>
                    {% else %}
                        <li><a class="nav-link" href="{% url 'accounts:login' %}" style="color: white" > Giriş </a></li>
                        <li><a class="nav-link" href="{% url 'accounts:register' %}" style="color: white" > Üye Ol </a></li>
                    {% endif %}
                </ul>

    </div>
    </div>

</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}Anasayfa - {{ block.super }}{% endblock %}

{% block body %}

<div class="container">
<div class="row">
    <div class="col-md-6" style="background-color: #0dcaf0; height: 100px" >1</div>
    <div class="col-md-6" style="background-color: #373b3e; height: 100px">2</div>

</div>

Hoşgeldin {{ request.user.get_fullname }}
</div>

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}